"""Add category

Revision ID: 7dfc859207aa
Revises: 
Create Date: 2022-07-28 15:50:08.628157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfc859207aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_name', sa.String(length=25), nullable=False))
    op.create_unique_constraint(None, 'category', ['category_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'category_name')
    # ### end Alembic commands ###
